[mongodb]
mongodb.anilkumar.shop

[catalogue]
catalogue.anilkumar.shop

[frontend]
frontend.anilkumar.shop

[redis]
redis.anilkumar.shop

[user]
user.anilkumar.shop

[cart]
cart.anilkumar.shop

[mysql]
mysql.anilkumar.shop

[shipping]
shipping.anilkumar.shop

[rabbitmq]
rabbitmq.anilkumar.shop

[payment]
payment.anilkumar.shop

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[localhost]
localhost