CART_HOST: cart.backend-{{ env }}.anilkumar.shop
USER_HOST: user.backend-{{ env }}.anilkumar.shop
RABBITMQ_HOST: rabbitmq-{{ env}}.anilkumar.shop
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123